language: groovy
jdk:
- openjdk17
sudo: false
branches:
  only:
  - master
  - develop
addons:
  apt:
    packages:
    - gdal-bin
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 15.5.0
  - npm -dd install
script:
  - echo "skipping tests"
  - ./gradlew war
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
  - secure: JhjPkLRqDfCzJLdzE9Tpm1kMYZsLmGUYmIuNE6561eKyqaavI8BLaqgS/bZ4dAiiwrWf3toLxisSyhfb3CRCUR2YijFJxqZ0kkBXlWR5sVnKtUM9QebCyDVt8I0RTpTXt3uKc+UZz4bl97UN4tWSdCp7UaXWVq5qcsAa19TFUHidjH/exkJ/fB1EK3IV+a3SG7Q7vXMJeuMFg1JPP0Do0s+5+XLjdPKfS7KB/2YNDTB66aAT0CNq+3rNJ08dJuCdVPi9hv0xWl2n5BRkkXtq/0hL4mjW/5Nxq4pOwCB38aliAuxVjaFv9f9U1ioQmrNTnQaGmZVpMRYVYsNsy5WVbZtwqjFP1ysUMCfGcStN3xILNfjtrWaSXm5AVgC/8kgURhE96DHymM6t3WSojpyqRDn3GNezPd71a/vAS4TGqMWfjXq6Jjwg7SR5uDiPbCGQGF515FBfjGkfeYVufKq8bjOMl3mcN8ZyfWTmNGtIJ0y8ztEDDxZeE0WyZxg3ZJ9ng8Tk0LvCpgaVrEH4MJy7WEqJXnqJ85+nHC/z47LEWSCJ+Q7b3HzEZtx5RvlZBJotOMic3ZpQeC5X83HafPIUF6McQQaqLqURlNW023c0KSWbjOtMeN4TAgc6ebZGyZDXVGfCHdDLnM4zUHPprVD0cPMgKh/QcRckCxDH4DymeAc=
  - secure: VM2/APT6iLs1WcwVenn4x3+cccZ7YnxoQsWdrR5G9cSyipWVvMd1Q5pT3VfV17+shHH1bbEvW9en9a0SRpQGpF456YWKAqnvOKrvI1jxYgMqOzbpQguFYalqYuc0OkKQeTDtq72H777bPEYeATaSYri3oXI1/5J3xllgwqcB2ax24ytHmwUbkH1a55AVHr2r8Ei9WIphEg2SsoMezt5jJCW7t4FZWN81A45qviBnSGXQIi474iaEe1XJGNQjAFP+1b8jjPmkIYPmDzAWMcJPT/Um6YwTq/qUt5e8dlMwq/NzftbbLtl2V7Z9lLmP7NoF/zxyq1oRmFLuRi7EjVPUAK6rSPl1/bLGN1AqpDqQEnmuY2M1tTgN0l6C+QaWCG+nsXnK3fjvgdV+QXEVXT2aTDrzWgJNxLU+XUOCEmlrBsxyJtXirb+4qO92FirkeVKNwZYWCdKhGjoOvchcq6jKPt6Ww2nJ7arlJ7MBGeNDVs3G5Z/ZOdwfs/KV8BuZYxd985wgM0OuC/pZb2uNPz7+x9p8nl3TI2lf2Dq+/fmOmQFa9eEVZyrWpTKNG0eOE8b7DXAQQ4jx2axiq8OGUirLXe0wmT1t1Gl+TwR6064YfTL8B2wfxpPvC4eWg3wy8cDxAPevzAf7gSpQtqxBbFJgEyld8CF4TsFyQx3XHZ0nD+s=
